version: '3'
services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "${DATABASE_PORT}:1433"
    environment:
      SA_PASSWORD: "${DATABASE_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - ./db-data:/var/opt/mssql
      - ./scripts:/scripts
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & sleep 30s
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${DATABASE_PASSWORD} -i /scripts/initial-script.sql
        